name: Create release

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          files: |
            CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.changelog.outputs.clean_changelog }}
          draf: false
          prerelease: false
          tag_name: ${{ steps.changelog.outputs.tag }}

      # Adding VITE_API_KEY as a secret
     - name: Set up environment variables
      run: |
      echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env.production
      echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}" >> .env.production
      echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}" >> .env.production
      echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}" >> .env.production
      echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}" >> .env.production
      echo "VITE_APP_ID=${{ secrets.VITE_APP_ID }}" >> .env.production
      echo "VITE_MEASUREMENT_ID=${{ secrets.VITE_MEASUREMENT_ID }}" >> .env.production
