name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login:ci --no-localhost --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Set Firebase Project Configuration
        run: |
          firebase functions:config:set \
            project.api_key="${{ secrets.FIREBASE_API_KEY }}" \
            project.auth_domain="${{ secrets.FIREBASE_AUTH_DOMAIN }}" \
            project.project_id="${{ secrets.FIREBASE_PROJECT_ID }}" \
            project.storage_bucket="${{ secrets.FIREBASE_STORAGE_BUCKET }}" \
            project.messaging_sender_id="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" \
            project.app_id="${{ secrets.FIREBASE_APP_ID }}" \
            project.measurement_id="${{ secrets.FIREBASE_MEASUREMENT_ID }}"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
